# Generated by Django 4.1.4 on 2023-08-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='column',
            new_name='col',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='type',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='y',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='x',
            new_name='row',
        ),
    ]
