# Generated by Django 4.1.4 on 2023-08-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_rename_column_storage_col_rename_type_storage_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='l1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='l2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='l3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='l4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='l5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
