# Generated by Django 4.1.4 on 2023-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_storage_info_lab_storage_info_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_info',
            name='mapid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
